[package]
name = "spring-apalis"
description = "Integration of rust application framework spring-rs and apalis"
version = "0.4.0"
categories = ["date-and-time"]
keywords = ["cron-scheduler", "task-scheduling", "cron-job", "spring"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
redis = ["apalis-redis"]
sql-postgres = ["apalis-sql", "apalis-sql/postgres"]
sql-sqlite = ["apalis-sql", "apalis-sql/sqlite"]
sql-mysql = ["apalis-sql", "apalis-sql/mysql"]

[dependencies]
spring = { path = "../spring", version = "0.4" }
tower-service = { workspace = true }
tower-layer = { workspace = true }
tokio = { workspace = true }
apalis = { workspace = true, features = ["limit"] }  # Limit for concurrency
apalis-redis = { workspace = true, optional = true } # Use redis for persistence
apalis-sql = { workspace = true, optional = true }   # Use redis for persistence
