[package]
name = "spring-stream"
description = "Integrate sea-streamer with spring-rs"
version = "0.4.0"
categories = ["concurrency"]
keywords = ["stream-processing", "stream", "redis-stream", "kafka", "spring"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring = { path = "../spring", version = "0.4" }
spring-macros = { path = "../spring-macros", version = "0.4" }
sea-streamer = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
schemars = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true, features = ["log"] }
inventory = { workspace = true }

[features]
default = ["sea-streamer/runtime-tokio", "sea-streamer/socket"]
kafka = ["sea-streamer/kafka"]
redis = ["sea-streamer/redis"]
file = ["sea-streamer/file"]
stdio = ["sea-streamer/stdio"]
json = ["sea-streamer/json", "serde_json"]
