[package]
name = "plugin-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
schemars = { workspace = true }

[build-dependencies]
spring = { path = "../../spring" }
# generate plugin config schema with all features enabled
# Enable all features for apalis
spring-apalis = { path = "../../spring-apalis", features = ["redis", "amqp", "sql-postgres", "sql-sqlite", "sql-mysql", "workflow", "board", "board-web"] }
spring-grpc = { path = "../../spring-grpc" }
# Enable all features for job
spring-job = { path = "../../spring-job", features = ["postgres_storage", "nats_storage"] }
spring-mail = { path = "../../spring-mail" }
# Enable common services for opendal (not all to avoid compilation issues)
spring-opendal = { path = "../../spring-opendal", features = ["services-fs", "services-memory", "services-s3", "services-oss", "services-cos", "services-azblob", "services-gcs", "services-obs", "layers-metrics", "layers-tracing"] }
# Enable all features for opentelemetry
spring-opentelemetry = { path = "../../spring-opentelemetry", features = ["jaeger", "zipkin", "more-resource", "grpc", "http"] }
# Enable all features for postgres
spring-postgres = { path = "../../spring-postgres", features = ["array-impls", "with-chrono-0_4", "with-serde_json-1", "with-time-0_3", "with-uuid-1"] }
spring-redis = { path = "../../spring-redis" }
# Enable all features for sa-token
spring-sa-token = { path = "../../spring-sa-token", features = ["memory", "with-web", "with-spring-redis", "openapi"] }
# Enable all features for sea-orm
spring-sea-orm = { path = "../../spring-sea-orm", features = ["with-web", "with-web-openapi", "mysql", "sqlite", "postgres"] }
# Enable all features for sqlx
spring-sqlx = { path = "../../spring-sqlx", features = ["postgres", "mysql", "sqlite", "with-json", "with-chrono", "with-rust_decimal", "with-bigdecimal", "with-uuid", "with-time"] }
# Enable all features for stream
spring-stream = { path = "../../spring-stream", features = ["kafka", "redis", "file", "stdio", "json"] }
# Enable all features for web
spring-web = { path = "../../spring-web", features = ["openapi", "openapi-redoc", "openapi-scalar", "openapi-swagger", "socket_io", "multipart", "ws"] }
