[package]
name = "multi-datasource-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-sea-orm = { path = "../../spring-sea-orm", features = [
    "postgres",
    "with-web",
] }
tokio = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }