[package]
name = "component-macro-example"
version = "0.1.0"
edition = "2021"

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
