[package]
name = "autumn-boot-redis"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis_rs = "0.9.0"
